# Many thanks for John, my personal jekyll-based portfolio & blog is base on his jekyll project
# project portal: https://github.com/panossakkos/personal-jekyll-theme/

#########################################
# NOTE:
# 1. space " " after the ":" is essential
#########################################

################################################################################################################################
# This section is the setting for markdown engine (it needs further configuration, still under construction
################################################################################################################################

# default markdown engine on GitHub
markdown: kramdown

# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge
#highlighter: pygments

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
################################################################################################################################

# NB! Set your site's url, otherwise stuff will break :)

url: "https://xinli.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)
# gh-pages project name (the url after the xinli.io)

#baseurl: /repository-name

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Xin Li"
title: "{ Xin Li }"
description: "IT & Coding related Blog for personal studying"
keywords: "IT, Coding, Programming, Hacking, Omega"
favicon: ""


########
# Blog #
########

# enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "omega"

syntax-highlight: True


###########
# Contact #
###########

email: "KratosOmega@iCloud.com"


##################
# Social Buttons #
##################

social:
  - title: "stack-overflow"
    url: "http://stackoverflow.com/users/6008493/kratos-omega?tab=profile"
  - title: "github"
    url: "https://github.com/KratosOmega"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/xin-li-30982b52?trk=nav_responsive_tab_profile"
  - title: "facebook"
    url: "https://www.facebook.com/profile.php?id=100012816881722"
  - title: "twitter"
    url: "https://twitter.com/Kratos_Omega"

############
# 404 page #
############

404-img: "/img/404.png"

##################
# GPG on Keybase #
##################

keybase-username: xinli
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page


################## Update This later ##################
#pages_list:
#  About: 'about'
#  Resume: 'resume'
#  Project: 'project'
#  Blog: 'latest-post'
#  Contact: 'contact'
################## Update This later ##################


# Exclusion list from the generated _site
# ignore any folders or files
exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
#  - jemoji


